### ISSUE TITLE
Can't authenticate using app.get('path', passport.authenticate('oauth'));

### ISSUE THREAD

**Issue by xtina** [jaredhanson/passport-oauth1#9]
When trying to redirect to "path", I get this error:

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
   at Error (native)
   at Sign.sign (crypto.js:279:26)
   at exports.OAuth._createSignature (/Users/Documents/node/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:211:64)
   at exports.OAuth._getSignature (/Users/Documents/node/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:90:15)
   at exports.OAuth._prepareParameters (/Users/Documents/node/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:300:16)
   at exports.OAuth._performSecureRequest (/Users/Documents/node/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:309:31)
   at exports.OAuth.getOAuthRequestToken (/Users/Documents/node/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:542:8)
   at OAuthStrategy.authenticate (/Users/Documents/node/node_modules/passport-oauth1/lib/strategy.js:243:17)
   at attempt (/Users/Documents/node/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
   at Passport.authenticate (/Users/Documents/node/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
   at Layer.handle [as handle_request] (/Users/cblack/Documents/node/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/Documents/node/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/Documents/node/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/Documents/node/node_modules/express/lib/router/layer.js:95:5)
   at /Users/Documents/node/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/Documents/node/node_modules/express/lib/router/index.js:330:12)

**Comment by jaredhanson** [comment]
There's not enough information here to pinpoint the issue to this project.  Closing.  If you can provide information that isolates the issue to this project, please reopen.

**Comment by patrickd-** [comment]
Ran into this error, seems to work with this:
```
- signatureMethod: "RSA-SHA1"
+ signatureMethod: 'HMAC-SHA1'
```
